= Jython Gradle Plugin
Jeroen van Erp
:jython_plugin_version: 0.1.0

image::https://travis-ci.org/hierynomus/jython-gradle-plugin.svg?branch=master[]

This plugin will scan and adapt your source files to include a provided header, e.g. a LICENSE file.  By default it will scan every source set and report warnings. It will also create format tasks, which will properly format and apply the specified header. A bulk of the logic comes from the maven-license-plugin.

This plugin will also report on the licenses of your dependencies.

== Usage
The `jython-gradle-plugin` will be published to http://bintray.com[] and will be available through the http://plugins.gradle.org/[Gradle plugin exchange]. This means that there are a few different usage scenarios listed below.

=== Gradle 2.1 and above
In your `build.gradle` file add:

[source,groovy,subs="verbatim,attributes"]
----
plugins {
    id "com.github.hierynomus.jython" version "{jython_plugin_version}"
}
----

=== Gradle 1.x/2.0
In your `build.gradle` file add:

[source,groovy,subs="verbatim,attributes"]
----
    buildscript {
        repositories {
            jcenter()
        }

        dependencies {
            classpath 'com.hierynomus.gradle.plugins:jython-gradle-plugin:{jython_plugin_version}'
        }
    }
----

== Example
The following example will download the `boto3` library from `pypi.python.org` and bundle it in your Jar file.

[source,groovy,subs="verbatim,attributes"]
----
plugins {
    id "java"
    id "com.github.hierynomus.jython" version "{jython_plugin_version}"
}

dependencies {
  jython ":boto3:1.1.3"
}
----

== Configuration
By default the following two repository-patterns have been defined for the plugin:

- +https://pypi.python.org/packages/source/${dep.name[0]}/${dep.name}/${dep.name}-${dep.version}.tar.gz+
- +https://github.com/${dep.group}/${dep.name}/archive/${dep.version}.tar.gz+

These can be overridden or extended using the `jython` extension. For instance:

[source,groovy,subs="verbatim,attributes"]
----
jython {
  sourceRepositories += `http://my.local.repo/${dep.name}/${dep.version}/${dep.name}-${dep.version}.tar.gz
}
----

== If a python module name differs from the artifact name.
In some cases, the python module name is not the same as the artifact name. In order to overcome this, you can use the `classifier` of the dependency to set the correct module name used for extraction. For instance:

----
dependencies {
  jython "jmespath:jmespath.py:0.7.1:jmespath"
  jython ":python-dateutil:2.4.2:dateutil"
}
----

== Changelog

=== v0.1.0
- Initial version supporting `pypi` and `github` library locations
